import { Section } from "@/types";

export const sections: Section[] = [
  {
    id: "section1",
    name: "Organisation & Entity Structure",
    description: "Understanding your organisational structure helps us assess multi-entity complexity and consolidation needs.",
    estimatedMinutes: 6,
    questions: [
      {
        id: "q1",
        type: "multiple-choice",
        label: "How many separate legal entities or subsidiaries do you operate?",
        helperText: "This helps us understand consolidation complexity. Some systems handle multi-entity reporting better than others.",
        required: true,
        options: [
          { label: "1-2", value: "1-2" },
          { label: "3-5", value: "3-5" },
          { label: "6-10", value: "6-10" },
          { label: "10+", value: "10+" },
        ],
      },
      {
        id: "q2",
        type: "yes-no-followup",
        label: "Do you need separate financial reporting (P&L, Balance Sheet) for each entity?",
        helperText: "Multi-entity consolidation is a key differentiator between ERP platforms.",
        required: true,
        followupQuestion: {
          id: "q2_followup",
          type: "number",
          label: "How many entities need individual reporting?",
          min: 1,
        },
      },
      {
        id: "q3",
        type: "yes-no-followup",
        label: "Do you operate across multiple locations or sites?",
        helperText: "Understanding your geographic footprint helps assess data access and performance requirements.",
        required: true,
        followupQuestion: {
          id: "q3_count",
          type: "number",
          label: "How many locations?",
          min: 1,
        },
      },
      {
        id: "q4",
        type: "multiple-choice",
        label: "What is your current organisational structure?",
        helperText: "This impacts how we structure the ERP and reporting.",
        required: true,
        options: [
          { label: "Single entity", value: "single" },
          { label: "Multiple entities under one parent", value: "multiple-parent" },
          { label: "Independent entities", value: "independent" },
          { label: "Other", value: "other" },
        ],
      },
      {
        id: "q5",
        type: "yes-no-followup",
        label: "Do you have shared services or centralised functions across entities?",
        helperText: "Shared services often require inter-entity transactions and allocation methods.",
        required: true,
        followupQuestion: {
          id: "q5_examples",
          type: "text",
          label: "Please provide examples (e.g., Shared IT, Finance, HR)",
          maxLength: 500,
        },
      },
    ],
  },
  {
    id: "section2",
    name: "Finance & Accounting Complexity",
    description: "Assessing financial complexity, chart of accounts structure, and accounting requirements.",
    estimatedMinutes: 7,
    questions: [
      {
        id: "q1",
        type: "multiple-choice",
        label: "How many chart of accounts segments do you currently use?",
        helperText: "Chart of accounts complexity affects implementation effort and reporting flexibility.",
        required: true,
        options: [
          { label: "Simple single COA", value: "simple" },
          { label: "Multiple COAs by entity", value: "multiple" },
          { label: "Segmented COA", value: "segmented" },
          { label: "Complex multi-dimensional", value: "complex" },
        ],
      },
      {
        id: "q2",
        type: "multiple-choice",
        label: "What is your current accounting system?",
        helperText: "Understanding your current system helps us plan migration complexity.",
        required: true,
        options: [
          { label: "Adept", value: "adept" },
          { label: "MYOB", value: "myob" },
          { label: "Xero", value: "xero" },
          { label: "Sage", value: "sage" },
          { label: "Other legacy system", value: "other-legacy" },
          { label: "Spreadsheets", value: "spreadsheets" },
        ],
      },
      {
        id: "q3",
        type: "multiple-choice",
        label: "How many years of historical financial data do you need to migrate?",
        helperText: "Historical data migration affects timeline and cost.",
        required: true,
        options: [
          { label: "Opening balances only", value: "opening" },
          { label: "1-2 years", value: "1-2" },
          { label: "3-5 years", value: "3-5" },
          { label: "5+ years", value: "5+" },
        ],
      },
      {
        id: "q4",
        type: "yes-no-followup",
        label: "Do you require multi-currency accounting?",
        helperText: "Multi-currency is standard in modern ERPs, but complexity varies.",
        required: true,
        followupQuestion: {
          id: "q4_currencies",
          type: "text",
          label: "Which currencies? (e.g., AUD, USD, EUR)",
          maxLength: 200,
        },
      },
      {
        id: "q5",
        type: "multiple-choice",
        label: "What is your financial reporting frequency?",
        helperText: "Reporting frequency impacts system performance and user access patterns.",
        required: true,
        options: [
          { label: "Monthly", value: "monthly" },
          { label: "Quarterly", value: "quarterly" },
          { label: "Annually", value: "annually" },
          { label: "Real-time/Ad-hoc", value: "realtime" },
        ],
      },
      {
        id: "q6",
        type: "scale",
        label: "Do you have complex revenue recognition requirements?",
        helperText: "Revenue recognition complexity can drive customisation needs.",
        required: true,
        min: 1,
        max: 5,
        scaleLabels: ["Simple cash basis", "", "Moderate", "", "Complex multi-element arrangements"],
      },
      {
        id: "q7",
        type: "multiple-choice",
        label: "How many open accounts payable and accounts receivable transactions do you typically have?",
        helperText: "Transaction volume affects migration planning and system performance.",
        required: true,
        options: [
          { label: "Less than 100", value: "<100" },
          { label: "100-500", value: "100-500" },
          { label: "500-2,000", value: "500-2000" },
          { label: "2,000+", value: "2000+" },
        ],
      },
    ],
  },
  {
    id: "section3",
    name: "Operations (Hospitality, Gaming, POS)",
    description: "Understanding operational complexity specific to RSL clubs—hospitality, gaming, and point-of-sale operations.",
    estimatedMinutes: 8,
    questions: [
      {
        id: "q1",
        type: "number",
        label: "How many point-of-sale (POS) locations do you operate?",
        helperText: "POS integration complexity varies significantly between ERP platforms.",
        required: true,
        min: 0,
      },
      {
        id: "q2",
        type: "multiple-select",
        label: "What POS systems do you currently use?",
        helperText: "POS integration is critical for hospitality operations and affects ERP selection.",
        required: true,
        options: [
          { label: "SwiftPOS", value: "swiftpos" },
          { label: "Other", value: "other" },
          { label: "None", value: "none" },
        ],
      },
      {
        id: "q2_keep",
        type: "yes-no-followup",
        label: "Do you plan to keep your current POS system or replace it?",
        helperText: "Understanding your POS strategy helps plan integration requirements.",
        required: false,
        followupQuestion: {
          id: "q2_replace",
          type: "text",
          label: "If replacing, which system are you considering?",
          maxLength: 200,
        },
      },
      {
        id: "q3",
        type: "yes-no-followup",
        label: "Do you operate gaming machines (pokies)?",
        helperText: "Gaming system integration requires real-time transaction handling.",
        required: true,
        followupQuestion: {
          id: "q3_system",
          type: "multiple-choice",
          label: "What gaming system do you use?",
          options: [
            { label: "IGT Gaming", value: "igt" },
            { label: "Other", value: "other" },
            { label: "Not sure", value: "unsure" },
          ],
        },
      },
      {
        id: "q4",
        type: "number",
        label: "How many gaming machines do you operate across all locations?",
        helperText: "Gaming transaction volume affects integration architecture.",
        required: false,
        min: 0,
      },
      {
        id: "q5",
        type: "yes-no-followup",
        label: "Do you have kitchen/hospitality management systems?",
        helperText: "Kitchen systems often require inventory and cost management integration.",
        required: true,
        followupQuestion: {
          id: "q5_system",
          type: "multiple-choice",
          label: "Which system?",
          options: [
            { label: "Cooking the Books", value: "cooking" },
            { label: "Other", value: "other" },
          ],
        },
      },
      {
        id: "q6",
        type: "multiple-choice",
        label: "How do you currently track inventory across your operations?",
        helperText: "Inventory management complexity affects ERP module requirements.",
        required: true,
        options: [
          { label: "Manual/spreadsheets", value: "manual" },
          { label: "Separate inventory system", value: "separate" },
          { label: "Part of POS", value: "pos" },
          { label: "Not tracked", value: "none" },
        ],
      },
      {
        id: "q7",
        type: "multiple-choice",
        label: "What is your typical inventory turnover?",
        helperText: "Inventory turnover frequency impacts real-time vs batch integration needs.",
        required: true,
        options: [
          { label: "Daily", value: "daily" },
          { label: "Weekly", value: "weekly" },
          { label: "Monthly", value: "monthly" },
          { label: "Seasonal", value: "seasonal" },
        ],
      },
      {
        id: "q8",
        type: "yes-no-followup",
        label: "Do you need real-time inventory visibility across locations?",
        helperText: "Real-time inventory requires robust integration architecture.",
        required: true,
        followupQuestion: {
          id: "q8_scale",
          type: "scale",
          label: "How important is real-time inventory?",
          min: 1,
          max: 5,
          scaleLabels: ["Nice to have", "", "Important", "", "Critical"],
        },
      },
    ],
  },
  {
    id: "section4",
    name: "Procure to Pay & Expenses",
    description: "Understanding procurement processes, approval workflows, and expense management.",
    estimatedMinutes: 6,
    questions: [
      {
        id: "q1",
        type: "multiple-choice",
        label: "How do you currently manage purchase orders?",
        helperText: "PO automation is a key ERP benefit and affects implementation scope.",
        required: true,
        options: [
          { label: "Paper-based", value: "paper" },
          { label: "Email", value: "email" },
          { label: "Spreadsheet", value: "spreadsheet" },
          { label: "System-based", value: "system" },
        ],
      },
      {
        id: "q2",
        type: "yes-no-followup",
        label: "Do you have purchase approval workflows?",
        helperText: "Approval workflows can be configured or require customisation depending on complexity.",
        required: true,
        followupQuestion: {
          id: "q2_complexity",
          type: "scale",
          label: "How complex are your approval workflows?",
          min: 1,
          max: 5,
          scaleLabels: ["Simple", "", "Moderate", "", "Very complex"],
        },
      },
      {
        id: "q3",
        type: "multiple-choice",
        label: "Are you using or planning to use Medius for procure-to-pay?",
        helperText: "Medius integration affects ERP selection and implementation phasing.",
        required: true,
        options: [
          { label: "Yes, fully deployed", value: "deployed" },
          { label: "Yes, partially deployed", value: "partial" },
          { label: "Yes, planning to use", value: "planning" },
          { label: "No", value: "no" },
        ],
      },
      {
        id: "q4",
        type: "multiple-choice",
        label: "How do you currently manage employee expenses?",
        helperText: "Expense management automation reduces manual work and improves compliance.",
        required: true,
        options: [
          { label: "Manual/paper", value: "manual" },
          { label: "Email", value: "email" },
          { label: "Spreadsheet", value: "spreadsheet" },
          { label: "System-based", value: "system" },
        ],
      },
      {
        id: "q5",
        type: "multiple-choice",
        label: "How many purchase orders do you process per month?",
        helperText: "PO volume affects system performance and workflow design.",
        required: true,
        options: [
          { label: "Less than 50", value: "<50" },
          { label: "50-200", value: "50-200" },
          { label: "200-500", value: "200-500" },
          { label: "500+", value: "500+" },
        ],
      },
      {
        id: "q6",
        type: "yes-no-followup",
        label: "Do you need multi-level approval workflows?",
        helperText: "Complex approval workflows may require customisation.",
        required: true,
        followupQuestion: {
          id: "q6_levels",
          type: "number",
          label: "How many approval levels?",
          min: 1,
          max: 10,
        },
      },
    ],
  },
  {
    id: "section5",
    name: "Payroll & Workforce",
    description: "Understanding payroll complexity and workforce management needs.",
    estimatedMinutes: 5,
    questions: [
      {
        id: "q1",
        type: "number",
        label: "How many employees do you have across all entities?",
        helperText: "Employee count affects licensing and integration volume.",
        required: true,
        min: 1,
      },
      {
        id: "q2",
        type: "multiple-choice",
        label: "What payroll system do you currently use?",
        helperText: "Payroll integration is typically required for accurate financial reporting.",
        required: true,
        options: [
          { label: "MicroPay", value: "micropay" },
          { label: "Humanforce", value: "humanforce" },
          { label: "Other", value: "other" },
          { label: "Manual", value: "manual" },
        ],
      },
      {
        id: "q3",
        type: "yes-no-followup",
        label: "Do you use time and attendance tracking?",
        helperText: "Time tracking integration affects labour cost allocation and reporting.",
        required: true,
        followupQuestion: {
          id: "q3_system",
          type: "multiple-choice",
          label: "Which system?",
          options: [
            { label: "Humanforce Time Target", value: "humanforce" },
            { label: "Other", value: "other" },
          ],
        },
      },
      {
        id: "q4",
        type: "yes-no-followup",
        label: "Do you need payroll integration with the ERP?",
        helperText: "Payroll integration ensures accurate labour cost reporting and financial consolidation.",
        required: true,
        followupQuestion: {
          id: "q4_requirements",
          type: "text",
          label: "What are your integration requirements?",
          maxLength: 500,
        },
      },
      {
        id: "q5",
        type: "multiple-choice",
        label: "How many pay runs do you process per month?",
        helperText: "Payroll frequency affects integration scheduling and data volume.",
        required: true,
        options: [
          { label: "Weekly", value: "weekly" },
          { label: "Fortnightly", value: "fortnightly" },
          { label: "Monthly", value: "monthly" },
          { label: "Multiple frequencies", value: "multiple" },
        ],
      },
    ],
  },
  {
    id: "section6",
    name: "Reporting, BI & FP&A",
    description: "Assessing reporting maturity, BI needs, and financial planning requirements.",
    estimatedMinutes: 7,
    questions: [
      {
        id: "q1",
        type: "number",
        label: "How many different reporting or BI tools do you currently use?",
        helperText: "Multiple BI tools indicate a need for better integrated reporting.",
        required: true,
        min: 0,
      },
      {
        id: "q2",
        type: "multiple-select",
        label: "What types of reports do you generate regularly?",
        helperText: "Report types help determine if native ERP reporting is sufficient or if separate BI is needed.",
        required: true,
        options: [
          { label: "Financial statements", value: "financial" },
          { label: "Operational dashboards", value: "operational" },
          { label: "Management reports", value: "management" },
          { label: "Compliance reports", value: "compliance" },
          { label: "Ad-hoc analysis", value: "ad-hoc" },
        ],
      },
      {
        id: "q3",
        type: "multiple-select",
        label: "Who needs access to financial reports?",
        helperText: "Report access requirements affect user licensing and security design.",
        required: true,
        options: [
          { label: "Finance team", value: "finance" },
          { label: "Management", value: "management" },
          { label: "Board", value: "board" },
          { label: "External stakeholders", value: "external" },
          { label: "All staff", value: "all" },
        ],
      },
      {
        id: "q4",
        type: "yes-no-followup",
        label: "Do you need real-time or near-real-time reporting?",
        helperText: "Real-time reporting requires robust data architecture and may favour cloud-native solutions.",
        required: true,
        followupQuestion: {
          id: "q4_scale",
          type: "scale",
          label: "How important is real-time reporting?",
          min: 1,
          max: 5,
          scaleLabels: ["Daily is fine", "", "Important", "", "Real-time critical"],
        },
      },
      {
        id: "q5",
        type: "multiple-choice",
        label: "Do you do financial planning and forecasting?",
        helperText: "FP&A requirements may drive need for additional planning tools beyond core ERP.",
        required: true,
        options: [
          { label: "Yes, annual budget", value: "annual" },
          { label: "Yes, quarterly forecasts", value: "quarterly" },
          { label: "Yes, rolling forecasts", value: "rolling" },
          { label: "Not currently", value: "no" },
        ],
      },
      {
        id: "q6",
        type: "yes-no-followup",
        label: "Do you need scenario modeling or 'what-if' analysis?",
        helperText: "Advanced planning features vary significantly between ERP platforms.",
        required: true,
        followupQuestion: {
          id: "q6_complexity",
          type: "scale",
          label: "How complex are your scenario modeling needs?",
          min: 1,
          max: 5,
          scaleLabels: ["Simple", "", "Moderate", "", "Very complex"],
        },
      },
      {
        id: "q7",
        type: "multiple-choice",
        label: "Are you considering a data warehouse or data lake?",
        helperText: "Data warehouse architecture affects long-term analytics capabilities and integration complexity.",
        required: true,
        options: [
          { label: "Yes, NetSuite analytics", value: "netsuite" },
          { label: "Yes, Azure/Fabric", value: "azure" },
          { label: "Yes, AWS", value: "aws" },
          { label: "Yes, Other", value: "other" },
          { label: "Not sure", value: "unsure" },
          { label: "No", value: "no" },
        ],
      },
    ],
  },
  {
    id: "section7",
    name: "Integrations & Data Architecture",
    description: "Understanding integration volume, complexity, and real-time requirements.",
    estimatedMinutes: 9,
    questions: [
      {
        id: "q1",
        type: "multiple-select",
        label: "Which external systems need to integrate with your ERP?",
        helperText: "Integration count and complexity significantly impacts ERP selection and implementation cost.",
        required: true,
        options: [
          { label: "SwiftPOS", value: "swiftpos" },
          { label: "IGT Gaming", value: "igt" },
          { label: "Humanforce", value: "humanforce" },
          { label: "Medius", value: "medius" },
          { label: "Cooking the Books", value: "cooking" },
          { label: "Bank feeds", value: "bank" },
          { label: "Other", value: "other" },
        ],
      },
      {
        id: "q2",
        type: "multiple-choice",
        label: "What is your current integration approach?",
        helperText: "Current integration methods help us plan migration and modernisation.",
        required: true,
        options: [
          { label: "Flat file transfers", value: "flat" },
          { label: "APIs", value: "apis" },
          { label: "Manual data entry", value: "manual" },
          { label: "Mix of approaches", value: "mix" },
        ],
      },
      {
        id: "q3",
        type: "yes-no-followup",
        label: "Do you have an existing integration platform or middleware?",
        helperText: "Existing integration platforms can be leveraged or may need replacement.",
        required: true,
        followupQuestion: {
          id: "q3_platform",
          type: "multiple-choice",
          label: "Which platform?",
          options: [
            { label: "IAPI Direct Services", value: "iapi" },
            { label: "Other", value: "other" },
            { label: "Not sure", value: "unsure" },
          ],
        },
      },
      {
        id: "q4",
        type: "multiple-choice",
        label: "How many transactions do your integrations process per day?",
        helperText: "Transaction volume affects integration architecture and performance requirements.",
        required: true,
        options: [
          { label: "Less than 1,000", value: "<1000" },
          { label: "1,000-10,000", value: "1000-10000" },
          { label: "10,000-50,000", value: "10000-50000" },
          { label: "50,000+", value: "50000+" },
        ],
      },
      {
        id: "q5",
        type: "multiple-select",
        label: "Which integrations require real-time or near-real-time data?",
        helperText: "Real-time requirements drive API-based integration architecture and may favour certain ERP platforms.",
        required: false,
        options: [
          { label: "SwiftPOS", value: "swiftpos" },
          { label: "IGT Gaming", value: "igt" },
          { label: "Humanforce", value: "humanforce" },
          { label: "Medius", value: "medius" },
          { label: "Cooking the Books", value: "cooking" },
          { label: "Bank feeds", value: "bank" },
          { label: "Other", value: "other" },
        ],
      },
      {
        id: "q6",
        type: "multiple-select",
        label: "Which systems can continue using flat file transfers?",
        helperText: "Flat file integrations are simpler but less flexible than APIs.",
        required: false,
        options: [
          { label: "SwiftPOS", value: "swiftpos" },
          { label: "IGT Gaming", value: "igt" },
          { label: "Humanforce", value: "humanforce" },
          { label: "Medius", value: "medius" },
          { label: "Cooking the Books", value: "cooking" },
          { label: "Bank feeds", value: "bank" },
          { label: "Other", value: "other" },
        ],
      },
      {
        id: "q7",
        type: "yes-no-followup",
        label: "Do you need bank feed integration?",
        helperText: "Bank feeds reduce manual reconciliation work and are standard in modern ERPs.",
        required: true,
        followupQuestion: {
          id: "q7_banks",
          type: "number",
          label: "How many bank accounts?",
          min: 1,
        },
      },
      {
        id: "q8",
        type: "text",
        label: "What is your data volume for integrations (transactions per day/week)?",
        helperText: "Data volume helps size integration infrastructure and affects cost.",
        required: false,
        maxLength: 500,
      },
      {
        id: "q9",
        type: "multiple-choice",
        label: "Do you need API management or will you build point-to-point integrations?",
        helperText: "API management becomes important with many integrations and affects architecture decisions.",
        required: true,
        options: [
          { label: "Point-to-point is fine", value: "point" },
          { label: "Need API management layer", value: "management" },
          { label: "Not sure", value: "unsure" },
        ],
      },
    ],
  },
  {
    id: "section8",
    name: "Risk, Compliance & Governance",
    description: "Understanding compliance requirements, audit needs, and governance structure.",
    estimatedMinutes: 5,
    questions: [
      {
        id: "q1",
        type: "multiple-select",
        label: "What compliance or regulatory requirements do you need to meet?",
        helperText: "Compliance requirements affect system configuration and reporting needs.",
        required: true,
        options: [
          { label: "Gaming regulations", value: "gaming" },
          { label: "Financial reporting standards", value: "financial" },
          { label: "Tax compliance", value: "tax" },
          { label: "Industry-specific", value: "industry" },
          { label: "Other", value: "other" },
        ],
      },
      {
        id: "q2",
        type: "yes-no-followup",
        label: "Do you need audit trails and change tracking?",
        helperText: "Audit trails are standard but granularity requirements vary.",
        required: true,
        followupQuestion: {
          id: "q2_scale",
          type: "scale",
          label: "How detailed do audit trails need to be?",
          min: 1,
          max: 5,
          scaleLabels: ["Basic", "", "Moderate", "", "Very detailed"],
        },
      },
      {
        id: "q3",
        type: "yes-no-followup",
        label: "Do you have role-based access control requirements?",
        helperText: "Access control complexity affects implementation and ongoing maintenance.",
        required: true,
        followupQuestion: {
          id: "q3_complexity",
          type: "scale",
          label: "How complex are your access control needs?",
          min: 1,
          max: 5,
          scaleLabels: ["Simple roles", "", "Moderate", "", "Complex matrix"],
        },
      },
      {
        id: "q4",
        type: "multiple-choice",
        label: "Are you considering anti-money laundering (AML) or transaction monitoring tools?",
        helperText: "AML tools may require specific integrations or data exports.",
        required: true,
        options: [
          { label: "Yes, required", value: "required" },
          { label: "Yes, planning", value: "planning" },
          { label: "Yes, considering", value: "considering" },
          { label: "No", value: "no" },
        ],
      },
      {
        id: "q5",
        type: "yes-no-followup",
        label: "Do you need segregation of duties controls?",
        helperText: "Segregation of duties is important for financial controls and affects user role design.",
        required: true,
        followupQuestion: {
          id: "q5_examples",
          type: "text",
          label: "Please provide examples",
          maxLength: 500,
        },
      },
      {
        id: "q6",
        type: "multiple-choice",
        label: "How often do you undergo external audits?",
        helperText: "Audit frequency affects reporting and data retention requirements.",
        required: true,
        options: [
          { label: "Annual", value: "annual" },
          { label: "Quarterly", value: "quarterly" },
          { label: "Ad-hoc", value: "ad-hoc" },
          { label: "Not applicable", value: "na" },
        ],
      },
    ],
  },
  {
    id: "section9",
    name: "Growth, Scalability & Strategy",
    description: "Understanding future growth plans and scalability needs.",
    estimatedMinutes: 5,
    questions: [
      {
        id: "q1",
        type: "yes-no-followup",
        label: "Do you plan to add new entities, locations, or business units in the next 3-5 years?",
        helperText: "Growth plans affect scalability requirements and may favour more flexible platforms.",
        required: true,
        followupQuestion: {
          id: "q1_details",
          type: "text",
          label: "Please provide details",
          maxLength: 500,
        },
      },
      {
        id: "q2",
        type: "yes-no-followup",
        label: "Do you anticipate significant transaction volume growth?",
        helperText: "Volume growth affects system performance requirements and cloud scalability.",
        required: true,
        followupQuestion: {
          id: "q2_scale",
          type: "scale",
          label: "What level of growth do you anticipate?",
          min: 1,
          max: 5,
          scaleLabels: ["Moderate growth", "", "Significant", "", "Rapid expansion"],
        },
      },
      {
        id: "q3",
        type: "multiple-choice",
        label: "What is your implementation timeline preference?",
        helperText: "Timeline affects phasing and may influence platform selection based on implementation complexity.",
        required: true,
        options: [
          { label: "6 months", value: "6" },
          { label: "12 months", value: "12" },
          { label: "18-24 months", value: "18-24" },
          { label: "Flexible", value: "flexible" },
        ],
      },
      {
        id: "q4",
        type: "scale",
        label: "Are you open to adopting ERP best practices vs replicating current processes?",
        helperText: "Process flexibility affects customisation needs and implementation cost.",
        required: true,
        min: 1,
        max: 5,
        scaleLabels: ["Replicate current", "", "Moderate change", "", "Adopt best practices"],
      },
      {
        id: "q5",
        type: "yes-no-followup",
        label: "Do you need the system to support future acquisitions or mergers?",
        helperText: "M&A activity requires flexible multi-entity architecture.",
        required: true,
        followupQuestion: {
          id: "q5_timeline",
          type: "text",
          label: "What is your M&A timeline?",
          maxLength: 200,
        },
      },
      {
        id: "q6",
        type: "multiple-select",
        label: "What is your priority for the ERP implementation? (Select all that apply, we'll ask you to rank them next)",
        helperText: "Priorities help weight decision criteria and may influence platform selection.",
        required: true,
        options: [
          { label: "Cost efficiency", value: "cost" },
          { label: "Speed to value", value: "speed" },
          { label: "Functionality fit", value: "functionality" },
          { label: "Scalability", value: "scalability" },
          { label: "Integration capability", value: "integration" },
          { label: "Partner support", value: "partner" },
        ],
      },
    ],
  },
  {
    id: "section10",
    name: "Decision Criteria & Priorities",
    description: "Capturing explicit decision criteria weightings to support a balanced, defensible comparison.",
    estimatedMinutes: 4,
    questions: [
      {
        id: "q1",
        type: "date",
        label: "When do you need to make a final ERP decision?",
        helperText: "Decision timeline affects discovery depth and implementation planning.",
        required: true,
      },
      {
        id: "q2",
        type: "date",
        label: "What is your target go-live date for Phase 1?",
        helperText: "Go-live target helps plan implementation phasing.",
        required: false,
      },
      {
        id: "q3",
        type: "percentage-sliders",
        label: "Please allocate importance to each decision criterion (total must equal 100%)",
        helperText: "These weightings help create a balanced, objective comparison between platforms.",
        required: true,
      },
      {
        id: "q4",
        type: "text",
        label: "Are there any deal-breakers or must-have requirements?",
        helperText: "Deal-breakers help filter platform options early in the evaluation.",
        required: false,
        maxLength: 1000,
      },
      {
        id: "q5",
        type: "text",
        label: "Who are the key decision-makers for this ERP selection?",
        helperText: "Understanding decision-makers helps plan stakeholder engagement.",
        required: false,
        maxLength: 500,
      },
    ],
  },
];
