import { Section } from "@/types";

export const sections: Section[] = [
  {
    id: "section1",
    name: "Organisation & Entity Structure",
    description: "Understanding your organisational structure helps us assess multi-entity complexity and consolidation needs.",
    estimatedMinutes: 8,
    questions: [
      {
        id: "q1",
        type: "text",
        label: "How many legal entities, operating entities, and reporting entities exist today?",
        helperText: "Understanding entity structure helps determine consolidation complexity.",
        required: true,
        maxLength: 500,
      },
      {
        id: "q2",
        type: "multiple-select",
        label: "For each entity/site, do you require separate:",
        helperText: "Separate requirements per entity affect ERP configuration and licensing.",
        required: true,
        options: [
          { label: "Bank accounts and payment runs", value: "bank-accounts" },
          { label: "Vendor agreements and pricing", value: "vendor-agreements" },
          { label: "Inventory valuation", value: "inventory-valuation" },
          { label: "Payroll cost allocation", value: "payroll-allocation" },
          { label: "Statutory vs management reporting", value: "reporting" },
        ],
      },
      {
        id: "q3",
        type: "multiple-choice",
        label: "Do entities transact with each other (shared services, recharges, staff, inventory transfers)?",
        helperText: "Inter-entity transactions require sophisticated ERP capabilities.",
        required: true,
        options: [
          { label: "Rare", value: "rare" },
          { label: "Monthly", value: "monthly" },
          { label: "Weekly", value: "weekly" },
          { label: "Daily", value: "daily" },
          { label: "No inter-entity transactions", value: "none" },
        ],
      },
      {
        id: "q4",
        type: "yes-no-followup",
        label: "Do intercompany transactions require automated elimination and balancing at close?",
        helperText: "Automated elimination is critical for accurate consolidated reporting.",
        required: true,
        followupQuestion: {
          id: "q4_details",
          type: "text",
          label: "Please provide details on elimination requirements",
          maxLength: 500,
        },
      },
      {
        id: "q5",
        type: "yes-no-followup",
        label: "Do entities require different fiscal calendars or reporting periods?",
        helperText: "Different fiscal calendars add complexity to consolidation.",
        required: true,
        followupQuestion: {
          id: "q5_details",
          type: "text",
          label: "Please describe the differences",
          maxLength: 500,
        },
      },
      {
        id: "q6",
        type: "yes-no-followup",
        label: "Do entities share a common chart of accounts, or diverge materially?",
        helperText: "Chart of accounts alignment affects reporting and consolidation.",
        required: true,
        followupQuestion: {
          id: "q6_details",
          type: "text",
          label: "Please describe the chart of accounts structure",
          maxLength: 500,
        },
      },
    ],
  },
  {
    id: "section2",
    name: "Finance & Accounting Complexity",
    description: "Assessing financial complexity, close processes, and accounting requirements.",
    estimatedMinutes: 7,
    questions: [
      {
        id: "q7",
        type: "multiple-choice",
        label: "Current month-end close duration:",
        helperText: "Close duration indicates process efficiency and system capability.",
        required: true,
        options: [
          { label: "<3 days", value: "<3" },
          { label: "3–5 days", value: "3-5" },
          { label: "6–10 days", value: "6-10" },
          { label: "10+ days", value: "10+" },
        ],
      },
      {
        id: "q8",
        type: "multiple-select",
        label: "Primary contributors to close delays (select all that apply):",
        helperText: "Understanding close bottlenecks helps prioritize ERP capabilities.",
        required: true,
        options: [
          { label: "Intercompany eliminations", value: "intercompany" },
          { label: "Manual journals", value: "manual-journals" },
          { label: "Reconciliations", value: "reconciliations" },
          { label: "External system data delays", value: "data-delays" },
          { label: "Approval bottlenecks", value: "approvals" },
        ],
      },
      {
        id: "q9",
        type: "multiple-choice",
        label: "Do you expect close effort to improve, stay the same, or worsen as the business grows?",
        helperText: "Growth expectations affect scalability requirements.",
        required: true,
        options: [
          { label: "Improve", value: "improve" },
          { label: "Stay the same", value: "same" },
          { label: "Worsen", value: "worsen" },
        ],
      },
      {
        id: "q10",
        type: "yes-no-followup",
        label: "Do you require multiple reporting books or parallel ledgers (e.g. management vs statutory)?",
        helperText: "Multiple books require sophisticated ERP capabilities.",
        required: true,
        followupQuestion: {
          id: "q10_details",
          type: "text",
          label: "Please describe the reporting book requirements",
          maxLength: 500,
        },
      },
      {
        id: "q11",
        type: "yes-no-followup",
        label: "Is multi-currency required now or within the next 3 years?",
        helperText: "Multi-currency affects ERP selection and implementation complexity.",
        required: true,
        followupQuestion: {
          id: "q11_currencies",
          type: "text",
          label: "Which currencies? (e.g., AUD, USD, EUR)",
          maxLength: 200,
        },
      },
    ],
  },
  {
    id: "section3",
    name: "Operations – Hospitality, Gaming, POS",
    description: "Understanding operational complexity specific to RSL clubs—hospitality, gaming, and point-of-sale operations.",
    estimatedMinutes: 10,
    questions: [
      {
        id: "q12",
        type: "multiple-choice",
        label: "Approximate daily transaction volumes generated by operations:",
        helperText: "Transaction volume affects system performance and integration architecture.",
        required: true,
        options: [
          { label: "<1k", value: "<1k" },
          { label: "1k–5k", value: "1k-5k" },
          { label: "5k–20k", value: "5k-20k" },
          { label: "20k+", value: "20k+" },
        ],
      },
      {
        id: "q13",
        type: "multiple-choice",
        label: "Are transactions posted to finance as:",
        helperText: "Transaction detail level affects ERP data model and reporting capabilities.",
        required: true,
        options: [
          { label: "Fully summarised", value: "summarised" },
          { label: "Mixed", value: "mixed" },
          { label: "Line-level detail", value: "line-level" },
        ],
      },
      {
        id: "q14",
        type: "yes-no-followup",
        label: "Do you need the ability to reprocess or replay operational data (e.g. corrected gaming files)?",
        helperText: "Reprocessing capability affects integration design and data architecture.",
        required: true,
        followupQuestion: {
          id: "q14_details",
          type: "text",
          label: "Please describe reprocessing requirements",
          maxLength: 500,
        },
      },
      {
        id: "q15",
        type: "multiple-select",
        label: "Do you require revenue analysis by:",
        helperText: "Revenue analysis dimensions affect reporting and data model requirements.",
        required: true,
        options: [
          { label: "Venue / outlet", value: "venue" },
          { label: "Department", value: "department" },
          { label: "Event", value: "event" },
          { label: "Member vs non-member", value: "member-type" },
          { label: "Promotions / comps", value: "promotions" },
          { label: "Tender type", value: "tender" },
        ],
      },
      {
        id: "q16",
        type: "multiple-choice",
        label: "Cash room requirements:",
        helperText: "Cash visibility requirements affect integration timing and architecture.",
        required: true,
        options: [
          { label: "Same-day ERP visibility required", value: "same-day" },
          { label: "Next-day acceptable", value: "next-day" },
        ],
      },
      {
        id: "q17",
        type: "yes-no-followup",
        label: "Do you require reconciliation across cash, EFTPOS, gaming, kiosks, vouchers with exception workflows?",
        helperText: "Reconciliation complexity affects workflow design and automation requirements.",
        required: true,
        followupQuestion: {
          id: "q17_details",
          type: "text",
          label: "Please describe reconciliation requirements",
          maxLength: 500,
        },
      },
      {
        id: "q18",
        type: "multiple-select",
        label: "Gaming integration requirements:",
        helperText: "Gaming integration requirements affect data architecture and retention policies.",
        required: true,
        options: [
          { label: "Daily summary only", value: "daily-summary" },
          { label: "Transaction-level detail", value: "transaction-level" },
          { label: "Regulatory or audit retention requirements", value: "retention" },
        ],
      },
      {
        id: "q19",
        type: "multiple-select",
        label: "Inventory and kitchen operations:",
        helperText: "Kitchen operations affect inventory management and cost tracking requirements.",
        required: true,
        options: [
          { label: "Recipe-level consumption and wastage tracking required", value: "recipe-tracking" },
          { label: "ERP should be source of truth for stock", value: "erp-source" },
          { label: "Kitchen system should be source of truth for stock", value: "kitchen-source" },
          { label: "Other system should be source of truth", value: "other-source" },
        ],
      },
    ],
  },
  {
    id: "section4",
    name: "Users, Roles & Access Model",
    description: "Understanding user roles, access requirements, and security model.",
    estimatedMinutes: 8,
    questions: [
      {
        id: "q20",
        type: "text",
        label: "For each role group (Finance, Venue Managers, Dept Heads, HR/Payroll, Exec/Board, Audit), specify access requirements:",
        helperText: "Role-based access affects licensing, security design, and workflow configuration.",
        required: true,
        maxLength: 2000,
      },
      {
        id: "q21",
        type: "yes-no-followup",
        label: "Do you require external or non-employee access (auditors, board, consultants)?",
        helperText: "External access affects authentication and licensing requirements.",
        required: true,
        followupQuestion: {
          id: "q21_details",
          type: "text",
          label: "Please describe external access requirements",
          maxLength: 500,
        },
      },
      {
        id: "q22",
        type: "yes-no-followup",
        label: "Are there shared workstations or terminals used by multiple staff?",
        helperText: "Shared workstations affect authentication and session management.",
        required: true,
        followupQuestion: {
          id: "q22_details",
          type: "text",
          label: "Please describe shared workstation usage",
          maxLength: 500,
        },
      },
      {
        id: "q23",
        type: "yes-no-followup",
        label: "Are there segregation-of-duties rules that must be enforced?",
        helperText: "Segregation of duties affects role design and workflow configuration.",
        required: true,
        followupQuestion: {
          id: "q23_details",
          type: "text",
          label: "Please describe segregation of duties requirements",
          maxLength: 500,
        },
      },
    ],
  },
  {
    id: "section5",
    name: "Integrations & Data Flow",
    description: "Understanding integration volume, complexity, and real-time requirements.",
    estimatedMinutes: 10,
    questions: [
      {
        id: "q24",
        type: "text",
        label: "For each system (POS, gaming, HR/time, payroll, P2P, cash mgmt, kitchen, BI), specify:",
        helperText: "Integration capabilities affect ERP selection and implementation approach.",
        required: true,
        maxLength: 2000,
      },
      {
        id: "q25",
        type: "multiple-select",
        label: "Which data must be near real-time?",
        helperText: "Real-time requirements drive integration architecture decisions.",
        required: true,
        options: [
          { label: "Sales", value: "sales" },
          { label: "Cash", value: "cash" },
          { label: "Payroll cost", value: "payroll-cost" },
          { label: "Inventory", value: "inventory" },
          { label: "Approvals", value: "approvals" },
        ],
      },
      {
        id: "q26",
        type: "text",
        label: "Approximate daily data volumes: POS line items / Gaming extracts / AP invoices / Timesheets",
        helperText: "Data volumes affect integration infrastructure sizing and performance.",
        required: true,
        maxLength: 1000,
      },
      {
        id: "q27",
        type: "text",
        label: "Integration failure handling: Who fixes failures today? Is non-technical retry important?",
        helperText: "Failure handling affects integration design and user experience.",
        required: true,
        maxLength: 1000,
      },
      {
        id: "q28",
        type: "text",
        label: "Who should own ongoing integration monitoring?",
        helperText: "Integration ownership affects support model and responsibilities.",
        required: true,
        maxLength: 500,
      },
    ],
  },
  {
    id: "section6",
    name: "Reporting, Planning & Analytics",
    description: "Assessing reporting maturity, BI needs, and financial planning requirements.",
    estimatedMinutes: 8,
    questions: [
      {
        id: "q29",
        type: "text",
        label: "Top operational reports required (venue managers).",
        helperText: "Operational reporting requirements affect ERP reporting capabilities needed.",
        required: true,
        maxLength: 1000,
      },
      {
        id: "q30",
        type: "text",
        label: "Top finance reports required (month-end).",
        helperText: "Finance reporting requirements affect ERP configuration and reporting tools.",
        required: true,
        maxLength: 1000,
      },
      {
        id: "q31",
        type: "text",
        label: "Top board/executive reports required.",
        helperText: "Executive reporting affects dashboard and BI requirements.",
        required: true,
        maxLength: 1000,
      },
      {
        id: "q32",
        type: "multiple-choice",
        label: "Where do most reporting rules live today?",
        helperText: "Reporting location affects migration and configuration requirements.",
        required: true,
        options: [
          { label: "Spreadsheets", value: "spreadsheets" },
          { label: "ERP", value: "erp" },
          { label: "Separate reporting layer", value: "separate" },
        ],
      },
      {
        id: "q33",
        type: "yes-no-followup",
        label: "Do finance users need to self-build reports without IT involvement?",
        helperText: "Self-service reporting affects ERP selection and user training requirements.",
        required: true,
        followupQuestion: {
          id: "q33_details",
          type: "text",
          label: "Please describe self-service reporting requirements",
          maxLength: 500,
        },
      },
      {
        id: "q34",
        type: "multiple-choice",
        label: "How frequently is forecasting performed?",
        helperText: "Forecasting frequency affects planning tool requirements.",
        required: true,
        options: [
          { label: "Annual only", value: "annual" },
          { label: "Quarterly", value: "quarterly" },
          { label: "Rolling", value: "rolling" },
          { label: "Not currently", value: "none" },
        ],
      },
      {
        id: "q35",
        type: "multiple-select",
        label: "Which system should be the authoritative source for:",
        helperText: "Master data ownership affects integration design and data governance.",
        required: true,
        options: [
          { label: "Customer/member master", value: "customer" },
          { label: "Product/item master", value: "product" },
          { label: "Employee master", value: "employee" },
          { label: "COA and segments", value: "coa" },
        ],
      },
    ],
  },
  {
    id: "section7",
    name: "Payroll & Workforce Management",
    description: "Understanding payroll complexity and workforce management needs.",
    estimatedMinutes: 5,
    questions: [
      {
        id: "q36",
        type: "text",
        label: "Pay rule complexity: Awards, penalties, overtime, split shifts, allowances",
        helperText: "Pay rule complexity affects payroll system requirements and integration needs.",
        required: true,
        maxLength: 1000,
      },
      {
        id: "q37",
        type: "yes-no-followup",
        label: "Do you require daily roster vs actual labour variance reporting?",
        helperText: "Labour variance reporting affects integration and reporting requirements.",
        required: true,
        followupQuestion: {
          id: "q37_details",
          type: "text",
          label: "Please describe variance reporting requirements",
          maxLength: 500,
        },
      },
      {
        id: "q38",
        type: "multiple-choice",
        label: "Timesheet approval complexity:",
        helperText: "Approval complexity affects workflow configuration requirements.",
        required: true,
        options: [
          { label: "Single level", value: "single" },
          { label: "Multi-level", value: "multi" },
          { label: "Delegated approvals", value: "delegated" },
        ],
      },
    ],
  },
  {
    id: "section8",
    name: "Procure-to-Pay & Capex",
    description: "Understanding procurement processes, approval workflows, and capital expenditure tracking.",
    estimatedMinutes: 6,
    questions: [
      {
        id: "q39",
        type: "multiple-select",
        label: "Approval rules vary by:",
        helperText: "Approval complexity affects workflow configuration requirements.",
        required: true,
        options: [
          { label: "Entity", value: "entity" },
          { label: "Venue", value: "venue" },
          { label: "Category", value: "category" },
          { label: "Spend threshold", value: "threshold" },
          { label: "Capex vs opex", value: "capex-opex" },
        ],
      },
      {
        id: "q40",
        type: "multiple-select",
        label: "Invoice processing requirements:",
        helperText: "Invoice processing requirements affect P2P system configuration.",
        required: true,
        options: [
          { label: "2-way match", value: "2-way" },
          { label: "3-way match", value: "3-way" },
          { label: "Automated coding", value: "automated-coding" },
          { label: "Exception handling", value: "exception-handling" },
        ],
      },
      {
        id: "q41",
        type: "text",
        label: "Supplier governance requirements (preferred suppliers, contracts, restrictions).",
        helperText: "Supplier governance affects procurement workflow configuration.",
        required: true,
        maxLength: 1000,
      },
      {
        id: "q42",
        type: "multiple-select",
        label: "Capex tracking:",
        helperText: "Capex tracking requirements affect project and asset management configuration.",
        required: true,
        options: [
          { label: "Budget approval", value: "budget" },
          { label: "Project tracking", value: "project" },
          { label: "PO-to-asset creation", value: "po-to-asset" },
        ],
      },
    ],
  },
  {
    id: "section9",
    name: "Fixed Assets, Leases & Property",
    description: "Understanding fixed asset management, lease accounting, and property portfolio requirements.",
    estimatedMinutes: 5,
    questions: [
      {
        id: "q43",
        type: "text",
        label: "Approximate number of fixed assets and leases.",
        helperText: "Asset volume affects system performance and module requirements.",
        required: true,
        maxLength: 500,
      },
      {
        id: "q44",
        type: "yes-no-followup",
        label: "Multiple depreciation books required?",
        helperText: "Multiple depreciation books affect asset management configuration.",
        required: true,
        followupQuestion: {
          id: "q44_details",
          type: "text",
          label: "Please describe depreciation book requirements",
          maxLength: 500,
        },
      },
      {
        id: "q45",
        type: "yes-no-followup",
        label: "Asset transfers between entities required?",
        helperText: "Inter-entity asset transfers affect multi-entity configuration.",
        required: true,
        followupQuestion: {
          id: "q45_details",
          type: "text",
          label: "Please describe asset transfer requirements",
          maxLength: 500,
        },
      },
      {
        id: "q46",
        type: "yes-no-followup",
        label: "Property portfolio reporting required with separate P&Ls?",
        helperText: "Property portfolio reporting affects reporting and entity structure.",
        required: true,
        followupQuestion: {
          id: "q46_details",
          type: "text",
          label: "Please describe property portfolio reporting requirements",
          maxLength: 500,
        },
      },
    ],
  },
  {
    id: "section10",
    name: "Controls, Audit & Compliance",
    description: "Understanding compliance requirements, audit needs, and governance structure.",
    estimatedMinutes: 5,
    questions: [
      {
        id: "q47",
        type: "multiple-select",
        label: "Audit log requirements for:",
        helperText: "Audit logging requirements affect system configuration and data retention.",
        required: true,
        options: [
          { label: "GL postings", value: "gl-postings" },
          { label: "Approvals", value: "approvals" },
          { label: "Master data changes", value: "master-data" },
        ],
      },
      {
        id: "q48",
        type: "text",
        label: "Data retention requirements (years) for: Financial transactions / POS detail / Gaming extracts",
        helperText: "Data retention affects storage requirements and compliance configuration.",
        required: true,
        maxLength: 1000,
      },
      {
        id: "q49",
        type: "multiple-select",
        label: "Identity and access expectations:",
        helperText: "Access expectations affect authentication and licensing requirements.",
        required: true,
        options: [
          { label: "Domain-restricted access", value: "domain-restricted" },
          { label: "External guest access", value: "guest-access" },
        ],
      },
    ],
  },
  {
    id: "section11",
    name: "Fit, Risk & Decision Criteria",
    description: "Capturing explicit decision criteria weightings to support a balanced, defensible comparison.",
    estimatedMinutes: 8,
    questions: [
      {
        id: "q50",
        type: "multiple-choice",
        label: "Process approach preference:",
        helperText: "Process flexibility affects customisation needs and implementation cost.",
        required: true,
        options: [
          { label: "Adopt standard best practice where possible", value: "best-practice" },
          { label: "Replicate current processes", value: "replicate" },
        ],
      },
      {
        id: "q51",
        type: "text",
        label: "Customisation tolerance: List up to 5 non-negotiable workflows",
        helperText: "Non-negotiable workflows affect ERP selection and implementation approach.",
        required: true,
        maxLength: 2000,
      },
      {
        id: "q52",
        type: "multiple-choice",
        label: "Upgrade and change appetite: Importance of staying close to vendor standard",
        helperText: "Upgrade appetite affects customisation decisions and long-term maintenance.",
        required: true,
        options: [
          { label: "Very important", value: "very-important" },
          { label: "Important", value: "important" },
          { label: "Moderately important", value: "moderate" },
          { label: "Not important", value: "not-important" },
        ],
      },
      {
        id: "q53",
        type: "text",
        label: "Implementation constraints: Target go-live dates / Blackout periods",
        helperText: "Implementation constraints affect project planning and phasing.",
        required: true,
        maxLength: 1000,
      },
      {
        id: "q54",
        type: "priority-ranking",
        label: "Decision weightings (total must equal 100%):",
        helperText: "Drag and drop to rank these criteria from most important (top) to least important (bottom).",
        required: true,
      },
      {
        id: "q55",
        type: "text",
        label: "Deal-breakers: List up to 5 conditions that would stop the project",
        helperText: "Deal-breakers help filter platform options early in the evaluation.",
        required: true,
        maxLength: 2000,
      },
    ],
  },
];
